import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'phillip' at '12/20/16 11:57 PM' with Gradle 3.2.1
 *
 * @author phillip, @date 12/20/16 11:57 PM
 */
public class ApplicationTest {
    /*
    @Test public void testApplicationMethod() {
        final short VENDOR_ID = 0x16c0;
        final short PRODUCT_ID = 0x0486;
        Application classUnderTest = new Application();
        assertNull(classUnderTest.enumerateDevices(VENDOR_ID,PRODUCT_ID));
    }
    */
}
